# Generated by Django 4.1.2 on 2022-11-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_application',
            name='img',
        ),
    ]
