# Generated by Django 4.1.1 on 2022-10-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='AppBlogs',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='AppCategory',
        ),
        migrations.RenameField(
            model_name='appblogs',
            old_name='slug_post',
            new_name='slug_app_post',
        ),
        migrations.RenameField(
            model_name='appcategory',
            old_name='slug_name',
            new_name='slug_app_cat',
        ),
    ]
