# Generated by Django 4.1.1 on 2022-10-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_blogs_appblogs_rename_category_appcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppBlogs',
            new_name='Blogsapplications',
        ),
        migrations.RenameModel(
            old_name='AppCategory',
            new_name='Categoryapplications',
        ),
        migrations.RenameField(
            model_name='blogsapplications',
            old_name='slug_app_post',
            new_name='slug_postapplications',
        ),
        migrations.RenameField(
            model_name='categoryapplications',
            old_name='slug_app_cat',
            new_name='slug_nameapplications',
        ),
    ]
