# Generated by Django 4.1.2 on 2022-10-29 18:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_rename_appblogs_blogsapplications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsapplications',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
