# Generated by Django 4.1.1 on 2022-10-30 06:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_blogsapplications_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsapplications',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
