# Generated by Django 4.1.2 on 2022-10-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsdservices',
            old_name='slug_postDServices',
            new_name='slug_postdservices',
        ),
        migrations.RenameField(
            model_name='categorydservices',
            old_name='slug_nameDServices',
            new_name='slug_namedservices',
        ),
    ]
