# Generated by Django 4.1.1 on 2022-10-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs1',
            new_name='BlogsAuto',
        ),
        migrations.RenameModel(
            old_name='Category1',
            new_name='CategoryAuto',
        ),
        migrations.RenameField(
            model_name='blogsauto',
            old_name='slug_post1',
            new_name='slug_postAuto',
        ),
        migrations.RenameField(
            model_name='categoryauto',
            old_name='slug_name1',
            new_name='slug_nameAuto',
        ),
    ]
