# Generated by Django 4.1.1 on 2022-10-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0002_rename_blogs1_blogsauto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogsAuto',
            new_name='Blogsautomobiles',
        ),
        migrations.RenameModel(
            old_name='CategoryAuto',
            new_name='Categoryautomobiles',
        ),
        migrations.RenameField(
            model_name='blogsautomobiles',
            old_name='slug_postAuto',
            new_name='slug_postautomobiles',
        ),
        migrations.RenameField(
            model_name='categoryautomobiles',
            old_name='slug_nameAuto',
            new_name='slug_nameautomobiles',
        ),
    ]
