# Generated by Django 4.1.1 on 2022-10-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_blogs_slug_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blogsshopping',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoryshopping',
        ),
        migrations.RenameField(
            model_name='blogsshopping',
            old_name='slug_post',
            new_name='slug_postshopping',
        ),
        migrations.RenameField(
            model_name='categoryshopping',
            old_name='slug_name',
            new_name='slug_nameshopping',
        ),
    ]
